### ISSUE TITLE
こんばんは。

### ISSUE THREAD

**Issue by study-programm** [study-programm/steady-cafe#10]
皆さんこんばんは。

フォルダ外のファイルを消したいです

**Comment by kuimac** [comment]
こんばんは。お世話になっております。
本日はあいにくのお天気でしたね。洗濯物等干されていませんでしたか？

さて、本題ですが、フォルダ外のファイルとは具体的にどれでしょうか？

お忙しいとは思いますが、お返事いただけると幸いです。
よろしくお願いいたします。

**Comment by study-programm** [comment]
![image](https://user-images.githubusercontent.com/84725572/133258995-168a414e-984b-4456-87a5-40a3d49aee12.png)
ここになります

**Comment by kuimac** [comment]
それでしたら一つづつファイルを開いてゴミ箱マークをクリックすれば消せます。
![スクリーンショット 2021-09-14 21 48 25](https://user-images.githubusercontent.com/13941932/133260477-bccabb45-39fb-42ac-a4f6-e1aeade2fc70.png)

**Comment by study-programm** [comment]
@kuimac ありがとうございます！
