### ISSUE TITLE
scriptタグの読み込み位置修正

### ISSUE THREAD

**Issue by ikuy0204** [study-programm/steady-cafe#13]
scriptタグはbodyもしくはheadの中で読み込む。
`type="text/javascript"` は書かなくていい。書いてもいいけど、書くなら全部のタグに書く（揃ってないと気持ち悪いので）。

https://github.com/study-programm/steady-cafe/blob/81765f56c08e1c6a5ebb38ccffa21824d08b0c98/index.html#L222-L227

参考URL : https://developer.mozilla.org/ja/docs/Web/HTML/Element/html

**Comment by study-programm** [comment]
@ikuy0204 
承知しました。
確認させていただきます。

**Comment by study-programm** [comment]
@ikuy0204 

此方の件ですが
headでscriptタグを読み込むと反応しないので、bodyの最後に読み込ませないと動かないのですがこのままでも大丈夫でしょうか。

**Comment by study-programm** [comment]
type="text/javascript"
此方は消しました

**Comment by ikuy0204** [comment]
bodyの一番下であれば問題ないです。
headでも反応する書き方はあるはずですが、一旦OKです。そのあたりは調べてみてください。

**Comment by ikuy0204** [comment]
@study-programm 
こちらの issue に関しても作業完了しているように見えますので、@study-programm さんの方で問題なければ Close お願いします。

**Comment by study-programm** [comment]
@ikuy0204 承知致しました。
