### ISSUE TITLE
架空のサイトなので情報を書かない（ぼかす）

### ISSUE THREAD

**Issue by ikuy0204** [study-programm/steady-cafe#15]
一応架空のサイトなんで住所とか電話番号はぼかしときましょう。
03-xxxx-xxxx みたいな感じで。
https://github.com/study-programm/steady-cafe/blob/81765f56c08e1c6a5ebb38ccffa21824d08b0c98/index.html#L143-L153

**Comment by study-programm** [comment]
@ikuy0204 

承知しました。
隠しておきます。

**Comment by ikuy0204** [comment]
@study-programm 
もしかしてこちらの issue って終わってますか？
私の方では作業完了しているように見えました。
問題もないと思うので、もし作業が完了していましたら @study-programm の方で Close お願いします。

**Comment by study-programm** [comment]
@ikuy0204 そうでした！終わっていました！
すぐクローズします！ありがとうございます。
