### ISSUE TITLE
CSS JS IMAGES　はasestsフォルダの中に入れる

### ISSUE THREAD

**Issue by kuimac** [study-programm/steady-cafe#4]

**Comment by study-programm** [comment]
@kuimac すみませんasettsフォルダというのが初めてです
そんなの使うのですね

**Comment by remuwebv** [comment]
@study-programm 
assets ですね。WEB開発とかだと、assets はよくあります。
@kuimac さん的には、こういった構造が理想的なのでは？と思ったのだと思います。

* assets
  * css
  * js
  * images

**Comment by study-programm** [comment]
@remuwebv 了解です。

ちょっと上げなおしてみます。

**Comment by study-programm** [comment]
@kuimac @remuwebv あげなおしてみました。

**Comment by remuwebv** [comment]
@study-programm プルリクください。

**Comment by study-programm** [comment]
頑張って出してみます
@remuwebv

**Comment by study-programm** [comment]
@remuwebv プルリク調べましたが送り方わかりませんでした

**Comment by remuwebv** [comment]
@study-programm 
また「できました」と言っても、相手からは「どこまでできた」か分からない状態です。
なので、できたら「できました」と報告するのではなく、成果物のURLやスクショを添えて「できました」と報告するようにしましょう。

**Comment by study-programm** [comment]
@remuwebv 了解致しました。気を付けます。

**Comment by kuimac** [comment]
typoです💦正しくはremuさんのおっしゃっている通りassets です。
正解がないというのもその通りですが、私がPLだったらassetsで管理します。

ブランチの運用についてですが、masterには動作確認済みのもののみをマージしましょう。
また、masterに対してのコミットは原則禁止します。
タスクに着手する場合はブランチを切って作業をし、完了した場合はmasterに対してPRを出し、GitHub上でレビューを行いOKだったらmasterへマージしましょう。

※あくまで一例ですが、本番運用は上記のように行っている場合が多いです。

**Comment by study-programm** [comment]
@kuimac　とても難しいですが1つ1つ覚えられるように頑張ります

**Comment by kuimac** [comment]
LGTM

**Comment by study-programm** [comment]
@remuwebv 遅くなり申し訳ございません。
確認取れましたので閉じます。
