### ISSUE TITLE
headで読み込んでるcssの順序を適切にする

### ISSUE THREAD

**Issue by kuimac** [study-programm/steady-cafe#5]

**Comment by study-programm** [comment]
はい。分かりました！

**Comment by study-programm** [comment]
@kuimac 変えてみました。
どうでしょうか？

**Comment by remuwebv** [comment]
@study-programm 
プルリクください。
プルリクがないのであれば、該当ページを @kuimac さんに提示してください。

**Comment by study-programm** [comment]
@kuimac どうでしょうか？
![無題](https://user-images.githubusercontent.com/84725572/133272120-8b5be63b-1219-43eb-adf5-88df3010a02b.png)

**Comment by kuimac** [comment]
headで読み込むcssの詳細度は調べましたか？

**Comment by study-programm** [comment]
CSS詳細度でググったのですが、head でのググりはないです。
今から調べてみます。

**Comment by kuimac** [comment]
headで読み込むcssの順序の意図を説明してくださいですね。
詳細度は関係なかったです。すみません。

**Comment by study-programm** [comment]
@kuimac 遅くなりました！

1番最後に上書きされるので
①最初にリセットCSSでクリアにしておく
↓
②メインスタイルを当てる(モバイル基準ならモバイルを)
↓
③メインとは違うスタイルのcssを当てる

最後に書いたものが、1番優先されないといけない為
今回ではレスポンシブを当てる必要があるので1番最後に書きました。

**Comment by kuimac** [comment]
よく理解できてて良いと思います。
余裕があればcss設計を学びましょう。
リーダブルにコードが書けるようになります。

LGTM

**Comment by study-programm** [comment]
承知致しました。
