### ISSUE TITLE
[SP] ハンバーガーメニューで、メニュー項目をクリックしたら、メニューを閉じるようにする

### ISSUE THREAD

**Issue by remuwebv** [study-programm/steady-cafe#9]
@study-programm 
メニュー項目（Aboutとか）をクリックしても、メニューが閉じないので閉じるようにしてください

![スクリーンショット 2021-09-14 21 31 42](https://user-images.githubusercontent.com/90695317/133258014-34d91b2b-7be0-4992-96bf-d588d611f38a.png)

**Comment by study-programm** [comment]
@remuwebv 　スクロールするように設定しているんですけども、
どの辺りがよろしくないのかもう少し具体的にお聞きしたいです。

背景クリックしたら閉じていますかね？自分は出来ているのですがどうでしょうか

**Comment by remuwebv** [comment]
@study-programm 
スマホ版で実際に触ってみました？
（スマホじゃなくても、サイズ縮めてみた状態でも大丈夫ですが）

スクロールするのはいいんですが、メニューが閉じないので、スクロール先のコンテンツを見ることができないです。

**Comment by study-programm** [comment]
@remuwebv  なるほどです。

背景クリックしたら閉じるからいいかなと思ったんですけど微妙なのですね！

**Comment by study-programm** [comment]
@remuwebv お待たせしました

背景城にしてた部分もあるのでそこを変えてみました

**Comment by remuwebv** [comment]
@study-programm 
変えたURL or プルリクが欲しいですー

**Comment by study-programm** [comment]
@remuwebv お待たせしました。
此方になります。

引き続き作業をやってみます。
後はセレクタからのコードを全部書き直しました。

https://study-programm.github.io/steady-cafe/

**Comment by study-programm** [comment]
@remuwebv 此方処理したと思うのですが、起きてからコード貼って確認後クローズでも宜しいでしょうか？

**Comment by study-programm** [comment]
解決しました
